title: CSA Pages
description: "Class of 2026"
owner_name: Akhil Singamneni
github_username: Akhil353
github_repo: "akhil_2025" 
baseurl: "/akhil_2025"
future: true
# remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/Akhil353"}

# remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/about.md
  - navigation/csa.md
  - navigation/blog.md
  - navigation/search.md
